/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ftdi.usb;

class exampleJNI {
  public final static native long new_ftdi_context();
  public final static native long new_ftdi_eeprom();
  public final static native int ftdi_init(long jarg1);
  public final static native int ftdi_read_data(long jarg1, byte[] jarg2, int jarg3);
  public final static native int ftdi_write_data(long jarg1, byte[] jarg2, int jarg3);
  public final static native int ftdi_usb_open(long jarg1, int jarg2, int jarg3);
  public final static native int ftdi_set_baudrate(long jarg1, int jarg2);
  public final static native int ftdi_set_line_property(long jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int ftdi_set_bitmode(long jarg1, short jarg2, short jarg3);
  public final static native int ftdi_read_pins(long jarg1, byte[] jarg2);
  public final static native int ftdi_setflowctrl(long jarg1, int jarg2);
  public final static native int ftdi_usb_reset(long jarg1);
  public final static native void ftdi_deinit(long jarg1);
  public final static native void ftdi_set_usbdev(long jarg1, long jarg2);
  public final static native int ftdi_usb_find_all(long jarg1, long jarg2, int jarg3, int jarg4);
  public final static native void ftdi_list_free(long jarg1);
  public final static native int ftdi_usb_open_desc(long jarg1, int jarg2, int jarg3, String jarg4, String jarg5);
  public final static native int ftdi_usb_open_dev(long jarg1, long jarg2);
  public final static native int ftdi_usb_close(long jarg1);
  public final static native int ftdi_usb_purge_buffers(long jarg1);
  public final static native int ftdi_read_data_set_chunksize(long jarg1, long jarg2);
  public final static native int ftdi_read_data_get_chunksize(long jarg1, long jarg2);
  public final static native int ftdi_write_data_set_chunksize(long jarg1, long jarg2);
  public final static native int ftdi_write_data_get_chunksize(long jarg1, long jarg2);
  public final static native int ftdi_enable_bitbang(long jarg1, short jarg2);
  public final static native int ftdi_disable_bitbang(long jarg1);
  public final static native int ftdi_set_latency_timer(long jarg1, short jarg2);
  public final static native int ftdi_get_latency_timer(long jarg1, long jarg2);
  public final static native void ftdi_eeprom_initdefaults(long jarg1);
  public final static native int ftdi_eeprom_build(long jarg1, byte[] jarg2);
  public final static native int ftdi_read_eeprom(long jarg1, byte[] jarg2);
  public final static native int ftdi_write_eeprom(long jarg1, byte[] jarg2);
  public final static native int ftdi_erase_eeprom(long jarg1);
}
