/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ftdi.usb;

public class SWIGTYPE_p_usb_dev_handle {
  private long swigCPtr;

  protected SWIGTYPE_p_usb_dev_handle(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_usb_dev_handle() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_usb_dev_handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

